server:
  port: 9090

spring:
  profiles:
    active: pay_order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mq_learn?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启发布确认 P -> Exchange
    publisher-confirm-type: simple
    # 开启returnMessage回调 Exchange -> Queue
    publisher-returns: true

logging:
  level:
    com.limingliang.projects.rabbitmq: debug

mybatis:
  type-aliases-package: com.limingliang.projects.rabbitmq.domain
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
